export const GET_ADDRESS_LIST = 'GET/ADDRESS/LIST';
export const UPDATE_ADDRESS = 'UPDATE/ADDRESS';
export const UPDATE_DEFAULT_ADDRESS = 'UPDATE/DEFAULT/ADDRESS';
export const CREATE_ADDRESS = 'CREATE/ADDRESS';
export const DELETE_ADDRESS = 'DELETE/ADDRESS';
