/**
 * @name cartID
 * @type {string}
 */
export const CART_ID = 'GT_CART_ID'


export const GENERATE_CART_ID = "GENERATE_CART_ID"
export const OK_GENERATE_CART_ID = 'OK_GENERATE_CART_ID'
export const BAD_GENERATE_CART_ID = 'BAD_GENERATE_CART_ID'
export const DELETE_CART_LIST_OF_ITEM = 'DELETE_CART_LIST_OF_ITEM'
export const OK_DELETE_CART_LIST_OF_ITEM = 'OK_DELETE_CART_LIST_OF_ITEM'
export const BAD_DELETE_CART_LIST_OF_ITEM = 'BAD_DELETE_CART_LIST_OF_ITEM'

export const GET_CART_LIST = 'GET_CART_LIST'
export const OK_GET_CART_LIST   = 'OK_GET_CART_LIST'
export const BAD_GET_CART_LIST = 'BAD_GET_CART_LIST'

export const CART_LINE_ITEM_ADD = 'CART_LINE_ITEM_ADD'
export const OK_CART_LINE_ITEM_ADD = 'OK_CART_LINE_ITEM_ADD'
export const BAD_CART_LINE_ITEM_ADD = 'BAD_CART_LINE_ITEM_ADD'

export const PUT_CART_TOTAL_QTY = 'PUT_CART_TOTAL_QTY'
export const OK_PUT_CART_TOTAL_QTY = 'OK_PUT_CART_TOTAL_QTY'
export const BAD_PUT_CART_TOTAL_QTY = 'BAD_PUT_CART_TOTAL_QTY'

export const PUT_CART_QTY_ITEM = 'PUT_CART_QTY_ITEM'
export const OK_PUT_CART_QTY_ITEM = 'OK_PUT_CART_QTY_ITEM'
export const BAD_PUT_CART_QTY_ITEM = 'BAD_PUT_CART_QTY_ITEM'
