export const GET_PROD_COLL_CATEGORY = 'PRODUCT/COLLECTION_CATEGORY';
export const GET_PROD_COLL_SEARCH = 'PRODUCT/COLLECTION/SEARCH';
export const GET_PROD_COLL_OUR_CATEGORY = 'PRODUCT/COLLECTION/OUR-CATEGORY';
export const GET_PROD_COLL_LATEST = 'PRODUCT/COLLECTION/LATEST';
export const GET_PROD_COLL_LATEST_SHOW = 'PRODUCT/COLLECTION/LATEST-SHOW';

export const GET_PROD_BY_ID = 'PRODUCT/ID';
export const GET_PROD_RECOMMENDATION_BY_PROD_ID = 'GET/PRODUCT/RECOMMENDATION/BY/PRODUCT/ID';
